name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  run-tests:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "pypy3.9"
      - run: pip install -r requirements.txt
      - run: pytest

  build-docker-images:
    runs-on: self-hosted
    needs: run-tests
    steps:
      - uses: actions/checkout@v3
      - run: docker build . --file Dockerfile --tag ledangkhoalt/cicd-practicing
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ledangkhoalt/cicd-practicing
